### ISSUE TITLE
Node Error: TypeError: to.getUTCFullYear is not a function

### ISSUE THREAD

**Issue by JoshMolyneux** [ZitRos/datetime-difference#2]
Please see below. Using Discord.js.

![code](https://user-images.githubusercontent.com/43067376/53885297-4190a480-4015-11e9-983c-9394226951b6.png)
![error](https://user-images.githubusercontent.com/43067376/53885300-42c1d180-4015-11e9-94f2-7851ef937024.png)

**Comment by JoshMolyneux** [comment]
Can close issue. Just required me to use the date in `new Date()` format

**Comment by nikitaeverywhere** [comment]
Glad you’ve dealt with this. Yep, all examples in readme file show that you need the date object. However, passing unix timestamp would also be convenient, I’ll sleep on it.

Thanks!
